<a href="https://colab.research.google.com/github/LUCASDNORONHA/data_structures_algorithms_python/blob/master/AlgoritmosOrdenacao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **IA Expert Academy**


---

**Curso:** Estruturas de Dados e Algoritmos em Python

**Alunos:** Lucas Dias Noronha

# Algoritmos de Ordenação

## Bubble Sort

In [4]:
def bubble_sort(vetor):
    # Cria uma cópia do vetor para não modificar o original
    vetor_ordenado = vetor.copy()
    n = len(vetor_ordenado)

    for i in range(n):
        for j in range(0, n - i - 1):
            if vetor_ordenado[j] > vetor_ordenado[j + 1]:
                vetor_ordenado[j], vetor_ordenado[j + 1] = vetor_ordenado[j + 1], vetor_ordenado[j]

    return vetor_ordenado


In [7]:
import numpy as np

bubble_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [8]:
bubble_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
vetor = np.array([64, 34, 25, 12, 22, 11, 90])
vetor_ordenado = bubble_sort(vetor)
print(vetor_ordenado)

[11 12 22 25 34 64 90]


## Selection Sort

In [10]:
def selection_sort(vetor):
    n = len(vetor)

    for i in range(n):
        id_minimo = i
        for j in range(i + 1, n):
            if vetor[j] < vetor[id_minimo]:
                id_minimo = j
        vetor[i], vetor[id_minimo] = vetor[id_minimo], vetor[i]

    return vetor

In [11]:
selection_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [12]:
selection_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
vetor = [64, 34, 25, 12, 22, 11, 90]
vetor_ordenado = selection_sort(vetor)
print(vetor_ordenado)

[11, 12, 22, 25, 34, 64, 90]


## Insertion Sort

In [14]:
def insertion_sort(vetor):
    n = len(vetor)

    for i in range(1, n):
        marcado = vetor[i]

        j = i - 1
        while j >= 0 and marcado < vetor[j]:
            vetor[j + 1] = vetor[j]
            j -= 1
        vetor[j + 1] = marcado

    return vetor

In [15]:
insertion_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [16]:
insertion_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
vetor = [64, 34, 25, 12, 22, 11, 90]
vetor_ordenado = insertion_sort(vetor)
print(vetor_ordenado)

[11, 12, 22, 25, 34, 64, 90]


## Shell Sort

In [18]:
def shell_sort(vetor):
    n = len(vetor)
    intervalo = n // 2  # Inicialize o intervalo com metade do tamanho do vetor

    while intervalo > 0:
        for i in range(intervalo, n):
            temp = vetor[i]
            j = i

            # Faça a inserção com o intervalo apropriado
            while j >= intervalo and vetor[j - intervalo] > temp:
                vetor[j] = vetor[j - intervalo]
                j -= intervalo

            vetor[j] = temp  # Inserir o elemento marcado na posição correta

        intervalo //= 2  # Reduza o intervalo pela metade

    return vetor

In [19]:
shell_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [20]:
shell_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
shell_sort(np.array([8,5,1,4,2,3]))

array([1, 2, 3, 4, 5, 8])

In [22]:
vetor = [64, 34, 25, 12, 22, 11, 90]
vetor_ordenado = shell_sort(vetor)
print(vetor_ordenado)

[11, 12, 22, 25, 34, 64, 90]


## Merge Sort

In [26]:
def merge_sort(vetor):
    if len(vetor) > 1:
        divisao = len(vetor) // 2
        esquerda = vetor[:divisao]
        direita = vetor[divisao:]

        merge_sort(esquerda)
        merge_sort(direita)

        i = j = k = 0

        # Combinação das sublistas ordenadas
        while i < len(esquerda) and j < len(direita):
            if esquerda[i] < direita[j]:
                vetor[k] = esquerda[i]
                i += 1
            else:
                vetor[k] = direita[j]
                j += 1
            k += 1

        # Verifica se há elementos restantes em esquerda e direita
        while i < len(esquerda):
            vetor[k] = esquerda[i]
            i += 1
            k += 1
        while j < len(direita):
            vetor[k] = direita[j]
            j += 1
            k += 1

    return vetor

In [27]:
merge_sort(np.array([15, 34, 8, 3]))

array([3, 3, 3, 3])

In [28]:
merge_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [29]:
merge_sort(np.array([38, 27, 43, 3, 9, 82, 10]))

array([ 3,  3,  3,  3,  9, 10, 10])

In [30]:
vetor = [64, 34, 25, 12, 22, 11, 90]
vetor_ordenado = merge_sort(vetor)
print(vetor_ordenado)

[11, 12, 22, 25, 34, 64, 90]


## Quick Sort

In [31]:
def particao(vetor, inicio, final):
    pivo = vetor[final]
    i = inicio - 1

    for j in range(inicio, final):
        if vetor[j] <= pivo:
            i += 1
            vetor[i], vetor[j] = vetor[j], vetor[i]

    vetor[i + 1], vetor[final] = vetor[final], vetor[i + 1]
    return i + 1

def quick_sort(vetor, inicio, final):
    if inicio < final:
        posicao = particao(vetor, inicio, final)

        # Ordenação à esquerda e à direita do pivo
        quick_sort(vetor, inicio, posicao - 1)
        quick_sort(vetor, posicao + 1, final)

    return vetor

In [32]:
vetor = np.array([15, 34, 8, 3])
quick_sort(vetor, 0, len(vetor) - 1)

array([ 3,  8, 15, 34])

In [33]:
vetor = np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
quick_sort(vetor, 0, len(vetor) - 1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
vetor = [64, 34, 25, 12, 22, 11, 90]
vetor_ordenado = quick_sort(vetor, 0, len(vetor) - 1)
print(vetor_ordenado)

[11, 12, 22, 25, 34, 64, 90]


# Comparativo entre Algoritmos

In [37]:
import random

vetor = [round(random.random(), 4) for _ in range(5000)]

type(vetor)

list

In [38]:
vetor = np.array(vetor)
type(vetor)

numpy.ndarray

In [39]:
vetor[:5]

array([0.8882, 0.3705, 0.7734, 0.2368, 0.791 ])

In [40]:
len(vetor)

5000

In [41]:
%timeit bubble_sort(vetor.copy())

6.83 s ± 879 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [42]:
%timeit selection_sort(vetor.copy())

3.83 s ± 813 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [43]:
%timeit insertion_sort(vetor.copy())

3.16 s ± 799 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [44]:
%timeit shell_sort(vetor.copy())

71.6 ms ± 30.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
%timeit merge_sort(vetor.copy())

In [45]:
%timeit quick_sort(vetor.copy(), 0, len(vetor) - 1)

31.8 ms ± 5.79 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Vetor Ordenado

In [46]:
import numpy as np

class VetorOrdenado:
    def __init__(self, capacidade):
        self.capacidade = capacidade
        self.ultima_posicao = -1
        self.valores = np.empty(self.capacidade, dtype=float)

    def insere(self, valor):
        if self.ultima_posicao == self.capacidade - 1:
            print('Capacidade atingida')
            return

        posicao = 0

        # Encontre a posição correta para inserção usando busca binária
        for i in range(self.ultima_posicao + 1):
            if self.valores[i] > valor:
                break
            posicao = i

        # Desloque os valores maiores para abrir espaço para o novo valor
        for i in range(self.ultima_posicao, posicao - 1, -1):
            self.valores[i + 1] = self.valores[i]

        self.valores[posicao] = valor
        self.ultima_posicao += 1

    def mostra(self):
        for i in range(self.ultima_posicao + 1):
            print(self.valores[i], end=" ")
        print()

In [47]:
def insere_ordenado(valores):
  vetor = VetorOrdenado(len(valores))
  for i in range(len(valores)):
    vetor.insere(i)

In [48]:
%timeit insere_ordenado(vetor.copy())

2.74 s ± 723 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
